### ISSUE TITLE
Version 0.0.4?

### ISSUE THREAD

**Issue by Jaza** [judy2k/fictionary#2]
@judy2k any change you could publish a new version of fictionary, that includes my changes from #1 ?

**Comment by judy2k** [comment]
I ... thought I had! Let me check today.

**Comment by Jaza** [comment]
Right, so you did... sorry, I didn't check the "versions" tab in github, nor did I check pypi, I just saw that the version number in `.bumpversion.cfg` and `setup.py` hadn't been updated.
